version: "3.8"

networks:
  nginx_net:
    driver: bridge

services:
  proxy_reverso:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - nginx_net

  calculator01:
    image: heliandro/rest-api-spring-boot-dev:1.0.0
    networks:
      - nginx_net

  calculator02:
    image: heliandro/rest-api-spring-boot-dev:1.0.0
    networks:
      - nginx_net