version: "3.8"

networks:
  nginx_net:
    driver: bridge

services:
  proxy_reverso:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - nginx_net

  frontend:
    build:
      context: ./my-angular-app
      dockerfile: Dockerfile
    networks:
      - nginx_net

  ms_calculator01:
    build:
      context: ./ms-spring-boot
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
        - PROFILE=dev
    networks:
      - nginx_net

  ms_calculator02:
    build:
      context: ./ms-spring-boot
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
        - PROFILE=dev
    networks:
      - nginx_net